import type { AdminSupportTicket } from "../types/tickets";

export const adminSupportTicketsMock: AdminSupportTicket[] = [
  {
    id: "#27",
    requesterName: "Rodrigo Arichisake",
    subject: "Necesito ayuda para asignar nuevo contexto",
    status: "open",
    priority: "low",
    assignee: "Fergus Deutscher",
    createdAt: "26 Oct 2026",
  },
  {
    id: "#39",
    requesterName: "Chaplain Mandover",
    subject: "Error al crear contexto para practica de voz",
    status: "closed",
    priority: "medium",
    assignee: "Bodman Salvador",
    createdAt: "28 Oct 2026",
  },
  {
    id: "#47",
    requesterName: "Rodmny Arichisake",
    subject: "Campaign movil con notificaciones duplicadas",
    status: "pending",
    priority: "low",
    assignee: "Iwannnce McKcenzie",
    createdAt: "04 Nov 2026",
  },
  {
    id: "#52",
    requesterName: "Imnence McKcenzie",
    subject: "Solicitud de anuncio de servicio",
    status: "open",
    priority: "high",
    assignee: "Abraham Pigeon",
    createdAt: "09 Nov 2026",
  },
  {
    id: "#67",
    requesterName: "Douglas Iryphe",
    subject: "No puedo editar lecciones de vocabulario",
    status: "closed",
    priority: "low",
    assignee: "Fergus Deutscher",
    createdAt: "17 Nov 2026",
  },
  {
    id: "#92",
    requesterName: "Theodore Handle",
    subject: "Metodo de pago rechazado en renovacion",
    status: "review",
    priority: "medium",
    assignee: "Janice Pegperspry",
    createdAt: "25 Dec 2026",
  },
  {
    id: "#109",
    requesterName: "Ariela Tonn",
    subject: "Usuarios reportan progreso congelado",
    status: "open",
    priority: "high",
    assignee: "Yuki Morita",
    createdAt: "02 Jan 2027",
  },
  {
    id: "#114",
    requesterName: "Kenji Sato",
    subject: "Revision de audio en modulo speaking",
    status: "review",
    priority: "medium",
    assignee: "Rina Delgado",
    createdAt: "05 Jan 2027",
  },
  {
    id: "#121",
    requesterName: "Mila Romano",
    subject: "Peticion de desbloqueo de leccion premium",
    status: "pending",
    priority: "high",
    assignee: "Sergio Yamada",
    createdAt: "07 Jan 2027",
  },
  {
    id: "#130",
    requesterName: "Noah Becker",
    subject: "Consulta sobre historial de facturacion",
    status: "open",
    priority: "low",
    assignee: "Ana Fujimoto",
    createdAt: "10 Jan 2027",
  },
];
