import type { GrammarBoardSlot } from "../types";

export const GRAMMAR_BOARD_TOTAL = 21;

export const GRAMMAR_BOARD_CANVAS = {
  width: 100,
  height: 100,
} as const;

const GRAMMAR_BOARD_INSET_X = 3.5;
const GRAMMAR_BOARD_INSET_Y = 4.25;

function applyBoardInset(slot: GrammarBoardSlot): GrammarBoardSlot {
  const usableWidth = 100 - GRAMMAR_BOARD_INSET_X * 2;
  const usableHeight = 100 - GRAMMAR_BOARD_INSET_Y * 2;

  return {
    ...slot,
    x: GRAMMAR_BOARD_INSET_X + (slot.x * usableWidth) / 100,
    y: GRAMMAR_BOARD_INSET_Y + (slot.y * usableHeight) / 100,
    width: (slot.width * usableWidth) / 100,
    height: (slot.height * usableHeight) / 100,
  };
}

const GRAMMAR_BASE_SUGOROKU_SLOTS: readonly GrammarBoardSlot[] = [
  {
    order: 1,
    x: 78,
    y: 80,
    width: 22,
    height: 20,
    size: "corner",
    routeTier: "outer",
    curveDirection: 0,
  },
  {
    order: 2,
    x: 58,
    y: 80,
    width: 20,
    height: 20,
    size: "standard",
    routeTier: "outer",
    curveDirection: 0,
  },
  {
    order: 3,
    x: 40,
    y: 80,
    width: 18,
    height: 20,
    size: "standard",
    routeTier: "outer",
    curveDirection: 0,
  },
  {
    order: 4,
    x: 18,
    y: 80,
    width: 22,
    height: 20,
    size: "standard",
    routeTier: "outer",
    curveDirection: 0,
  },
  {
    order: 5,
    x: 0,
    y: 80,
    width: 18,
    height: 20,
    size: "corner",
    routeTier: "outer",
    curveDirection: 0,
  },
  {
    order: 6,
    x: 0,
    y: 58,
    width: 18,
    height: 22,
    size: "standard",
    routeTier: "outer",
    curveDirection: 0,
  },
  {
    order: 7,
    x: 0,
    y: 38,
    width: 18,
    height: 20,
    size: "standard",
    routeTier: "outer",
    curveDirection: 0,
  },
  {
    order: 8,
    x: 0,
    y: 18,
    width: 18,
    height: 20,
    size: "standard",
    routeTier: "outer",
    curveDirection: 0,
  },
  {
    order: 9,
    x: 0,
    y: 0,
    width: 18,
    height: 18,
    size: "corner",
    routeTier: "outer",
    curveDirection: 0,
  },
  {
    order: 10,
    x: 18,
    y: 0,
    width: 20,
    height: 18,
    size: "standard",
    routeTier: "outer",
    curveDirection: 0,
  },
  {
    order: 11,
    x: 38,
    y: 0,
    width: 22,
    height: 18,
    size: "standard",
    routeTier: "outer",
    curveDirection: 0,
  },
  {
    order: 12,
    x: 60,
    y: 0,
    width: 18,
    height: 18,
    size: "standard",
    routeTier: "outer",
    curveDirection: 0,
  },
  {
    order: 13,
    x: 78,
    y: 0,
    width: 22,
    height: 18,
    size: "corner",
    routeTier: "outer",
    curveDirection: 0,
  },
  {
    order: 14,
    x: 78,
    y: 18,
    width: 22,
    height: 18,
    size: "standard",
    routeTier: "outer",
    curveDirection: 0,
  },
  {
    order: 15,
    x: 78,
    y: 36,
    width: 22,
    height: 22,
    size: "standard",
    routeTier: "outer",
    curveDirection: 0,
  },
  {
    order: 16,
    x: 78,
    y: 58,
    width: 22,
    height: 22,
    size: "standard",
    routeTier: "outer",
    curveDirection: 0,
  },
  {
    order: 17,
    x: 36,
    y: 60,
    width: 42,
    height: 20,
    size: "standard",
    routeTier: "inner",
    curveDirection: 0,
  },
  {
    order: 18,
    x: 18,
    y: 36,
    width: 18,
    height: 44,
    size: "standard",
    routeTier: "inner",
    curveDirection: 0,
  },
  {
    order: 19,
    x: 18,
    y: 18,
    width: 42,
    height: 18,
    size: "standard",
    routeTier: "inner",
    curveDirection: 0,
  },
  {
    order: 20,
    x: 60,
    y: 18,
    width: 18,
    height: 42,
    size: "standard",
    routeTier: "inner",
    curveDirection: 0,
  },
  {
    order: 21,
    x: 36,
    y: 36,
    width: 24,
    height: 24,
    size: "goal",
    routeTier: "goal",
    curveDirection: 0,
  },
];

export const GRAMMAR_SUGOROKU_SLOTS: readonly GrammarBoardSlot[] =
  GRAMMAR_BASE_SUGOROKU_SLOTS.map(applyBoardInset);
